FROM node:18

WORKDIR /app

COPY package*.json ./

RUN npm install --force

COPY . .

ARG NEXT_PUBLIC_WC_PROJECT_ID
ENV NEXT_PUBLIC_WC_PROJECT_ID=$NEXT_PUBLIC_WC_PROJECT_ID

ARG NEXT_PUBLIC_HOSTED_URL
ENV NEXT_PUBLIC_HOSTED_URL=$NEXT_PUBLIC_HOSTED_URL

ARG API_HOST
ENV API_HOST=$API_HOST

ARG NEXT_PUBLIC_API_HOST
ENV NEXT_PUBLIC_API_HOST=$NEXT_PUBLIC_API_HOST

ARG NEXT_PUBLIC_MEROKU_API_KEY
ENV NEXT_PUBLIC_MEROKU_API_KEY=$NEXT_PUBLIC_MEROKU_API_KEY

ARG API_PATH
ENV API_PATH=$API_PATH

ARG API_VERSION
ENV API_VERSION=$API_VERSION

ARG NEXT_PUBLIC_HOST_PATH
ENV NEXT_PUBLIC_HOST_PATH=$NEXT_PUBLIC_HOST_PATH

RUN npm run build

EXPOSE 3000

CMD ["npm", "run", "start"]